### ISSUE TITLE
no duration filtering is applied ?

### ISSUE THREAD

**Issue by hassony2** [athaddius/STIRLoader#2]
Hi,

I hope you are having a good day :)
Looking into the code, it seems that the duration filtering is not applied as [tofilter=False](https://github.com/athaddius/STIRLoader/blob/4a2c5244ace5017ea39112666dc70f3755169ad1/STIRLoader/STIRLoader.py#L128) by default and not overriden in STIRStereoClip (see [here](https://github.com/athaddius/STIRLoader/blob/4a2c5244ace5017ea39112666dc70f3755169ad1/STIRLoader/STIRLoader.py#L161) ?
Is this intended (my understanding was that the evaluation would be applied to samples < 12 seconds).

**Comment by athaddius** [comment]
Likewise to yourself, wishing a great day!
Thank you for asking. In the dataset release paper, we filtered samples to less than 12 seconds for metrics reported. In the challenge, there will be sequences up to 4 minutes: https://www.synapse.org/Synapse:syn54126082/wiki/626920

The length distribution of the testing split is very similar to the validation set, so the amount of clips with that length (>12s) is fewer than the amount of shorter clips.

Let me know if this makes sense, and I can close it if so.

**Comment by hassony2** [comment]
Thank you for the quick response, that makes a lot of sense :)

In this case, for validation results do you also recommend to filtering to samples <4minutes to match the test setup as closely as possible ?

**Comment by athaddius** [comment]
Absolutely, I would recommend exactly that!

**Comment by hassony2** [comment]
Thank you :) Closing given the provided answer !
